<?php

namespace Database\Seeders;

use App\Models\Cliente;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clientes = [
            [
                'nombre_empresa' => 'Vela Sport Fishing & Tours',
                'tipo_empresa' => 'servicios',
                'industria' => 'turismo',
                'descripcion' => 'Empresa dedicada a tours de pesca deportiva y excursiones marítimas en la costa del Pacífico.',
                'fecha_registro' => '2024-06-15',
                'fecha_creacion' => '2024-06-10',
                'estado_cuenta' => 'activo',
                'correo' => 'contacto@velasportfishing.com',
                'telefono' => '+52 322 123 4567',
                'whatsapp' => '+52 322 123 4567',
                'pais' => 'México',
                'estado' => 'Jalisco',
                'ciudad' => 'Puerto Vallarta',
                'direccion' => 'Marina Vallarta, Muelle 3, Local 15',
                'codigo_postal' => '48354',
                'nombre_sitio' => 'velasportfishing.com',
                'url_sitio' => 'https://velasportfishing.com',
                'hosting' => 'Hostinger',
                'dominio_expira' => '2025-06-15',
                'redes_sociales' => [
                    ['red' => 'facebook', 'url' => 'https://facebook.com/velasportfishing', 'activo' => true],
                    ['red' => 'instagram', 'url' => 'https://instagram.com/velasportfishing', 'activo' => true],
                ],
                'notas' => 'Cliente premium con contrato anual.',
            ],
            [
                'nombre_empresa' => 'Tacos El Güero',
                'tipo_empresa' => 'comercio',
                'industria' => 'gastronomia',
                'descripcion' => 'Taquería tradicional con más de 20 años de experiencia en la ciudad.',
                'fecha_registro' => '2024-08-01',
                'fecha_creacion' => '2024-07-28',
                'estado_cuenta' => 'activo',
                'correo' => 'info@tacoselguero.mx',
                'telefono' => '+52 33 1234 5678',
                'whatsapp' => '+52 33 1234 5678',
                'pais' => 'México',
                'estado' => 'Jalisco',
                'ciudad' => 'Guadalajara',
                'direccion' => 'Av. Chapultepec 456, Col. Americana',
                'codigo_postal' => '44160',
                'nombre_sitio' => 'tacoselguero.mx',
                'url_sitio' => 'https://tacoselguero.mx',
                'hosting' => 'GoDaddy',
                'dominio_expira' => '2025-08-01',
                'redes_sociales' => [
                    ['red' => 'instagram', 'url' => 'https://instagram.com/tacoselguero', 'activo' => true],
                    ['red' => 'tiktok', 'url' => 'https://tiktok.com/@tacoselguero', 'activo' => true],
                ],
                'notas' => 'Interesado en publicidad en redes sociales.',
            ],
            [
                'nombre_empresa' => 'Clínica Dental Sonrisas',
                'tipo_empresa' => 'servicios',
                'industria' => 'salud',
                'descripcion' => 'Clínica dental especializada en ortodoncia y estética dental.',
                'fecha_registro' => '2024-05-20',
                'fecha_creacion' => '2024-05-15',
                'fecha_cotizacion' => '2024-05-10',
                'estado_cuenta' => 'pendiente',
                'correo' => 'citas@clinicasonrisas.com',
                'telefono' => '+52 55 9876 5432',
                'telefono_alternativo' => '+52 55 1234 0000',
                'whatsapp' => '+52 55 9876 5432',
                'pais' => 'México',
                'estado' => 'CDMX',
                'ciudad' => 'Ciudad de México',
                'direccion' => 'Insurgentes Sur 1234, Col. Del Valle',
                'codigo_postal' => '03100',
                'nombre_sitio' => 'clinicasonrisas.com',
                'url_sitio' => 'https://clinicasonrisas.com',
                'hosting' => 'Bluehost',
                'dominio_expira' => '2025-05-20',
                'redes_sociales' => [
                    ['red' => 'facebook', 'url' => 'https://facebook.com/clinicasonrisas', 'activo' => true],
                ],
                'notas' => 'Esperando aprobación de cotización para rediseño web.',
            ],
            [
                'nombre_empresa' => 'Tech Solutions MX',
                'tipo_empresa' => 'tecnologia',
                'industria' => 'tecnologia',
                'descripcion' => 'Empresa de desarrollo de software y consultoría tecnológica.',
                'fecha_registro' => '2024-03-10',
                'fecha_creacion' => '2024-03-05',
                'fecha_cotizacion' => '2024-03-01',
                'fecha_factura' => '2024-03-15',
                'estado_cuenta' => 'activo',
                'correo' => 'hola@techsolutionsmx.com',
                'telefono' => '+52 81 2345 6789',
                'whatsapp' => '+52 81 2345 6789',
                'pais' => 'México',
                'estado' => 'Nuevo León',
                'ciudad' => 'Monterrey',
                'direccion' => 'Torre Avalanz, Piso 12, San Pedro',
                'codigo_postal' => '66260',
                'nombre_sitio' => 'techsolutionsmx.com',
                'url_sitio' => 'https://techsolutionsmx.com',
                'hosting' => 'AWS',
                'dominio_expira' => '2026-03-10',
                'redes_sociales' => [
                    ['red' => 'linkedin', 'url' => 'https://linkedin.com/company/techsolutionsmx', 'activo' => true],
                    ['red' => 'twitter', 'url' => 'https://twitter.com/techsolmx', 'activo' => true],
                ],
                'notas' => 'Cliente corporativo con soporte prioritario.',
            ],
            [
                'nombre_empresa' => 'Boutique La Elegante',
                'tipo_empresa' => 'comercio',
                'industria' => 'retail',
                'descripcion' => 'Tienda de ropa y accesorios de moda para dama.',
                'fecha_registro' => '2024-09-01',
                'estado_cuenta' => 'suspendido',
                'correo' => 'ventas@laelegante.com',
                'telefono' => '+52 999 123 4567',
                'pais' => 'México',
                'estado' => 'Yucatán',
                'ciudad' => 'Mérida',
                'direccion' => 'Paseo Montejo 789, Centro',
                'codigo_postal' => '97000',
                'nombre_sitio' => 'laelegante.com',
                'url_sitio' => 'https://laelegante.com',
                'hosting' => 'Hostinger',
                'dominio_expira' => '2024-12-01',
                'redes_sociales' => [
                    ['red' => 'instagram', 'url' => 'https://instagram.com/boutiquelaelegante', 'activo' => false],
                    ['red' => 'facebook', 'url' => 'https://facebook.com/laelegante', 'activo' => false],
                ],
                'notas' => 'Cuenta suspendida por falta de pago. Contactar para reactivar.',
            ],
            [
                'nombre_empresa' => 'Academia de Idiomas Global',
                'tipo_empresa' => 'servicios',
                'industria' => 'educacion',
                'descripcion' => 'Centro de enseñanza de idiomas con clases presenciales y en línea.',
                'fecha_registro' => '2024-07-15',
                'fecha_creacion' => '2024-07-10',
                'estado_cuenta' => 'activo',
                'correo' => 'info@academiaglobal.edu.mx',
                'telefono' => '+52 222 456 7890',
                'telefono_alternativo' => '+52 222 456 7891',
                'whatsapp' => '+52 222 456 7890',
                'pais' => 'México',
                'estado' => 'Puebla',
                'ciudad' => 'Puebla',
                'direccion' => 'Blvd. Atlixco 2500, Angelópolis',
                'codigo_postal' => '72810',
                'nombre_sitio' => 'academiaglobal.edu.mx',
                'url_sitio' => 'https://academiaglobal.edu.mx',
                'hosting' => 'DigitalOcean',
                'dominio_expira' => '2025-07-15',
                'redes_sociales' => [
                    ['red' => 'facebook', 'url' => 'https://facebook.com/academiaglobal', 'activo' => true],
                    ['red' => 'instagram', 'url' => 'https://instagram.com/academiaglobal', 'activo' => true],
                    ['red' => 'youtube', 'url' => 'https://youtube.com/@academiaglobal', 'activo' => true],
                ],
                'notas' => 'Contrato anual para gestión de redes sociales y mantenimiento web.',
            ],
        ];

        foreach ($clientes as $cliente) {
            Cliente::create($cliente);
        }
    }
}
